# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Axel Rock
subtitle: Front-end developer / iOS & Web
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm Axel
  I am a creative developer and traveller from France.
  I now live in Stockholm and work at Bannerboy.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://rock.bzh" # the base hostname & protocol for your site

contact:
  email:      axel@rock.bzh
  twitter:    nineties_panda
  linkedin:   axelrock
  phone:      +46 720 386 898
  instagram:  axel.rock

# Build settings
markdown: kramdown
